spring:
  datasource:
    url: jdbc:mysql://localhost:3306/frontend
    username: root
    password: 123456
  sql:
    init:
      ode: always
      encoding: UTF-8
interceptor:
  key: abcdefghijklmnopqrstuvwxyz0123456789
  mode: NONE
  pass: /api/loginJwt,/api/loginSession
logging:
  level:
    com:
      itheima.mapper: debug